name: xEffects
version: 1.0
main: rip.oxen.xeffects.xEffects
authors: [Oxen Development]
commands:
  effects:
    description: Open xEffects GUI
  sp:
    description: Toggle on/off speed
  fr:
    aliases: [fireres, res]
    description: Toggle on/off fire res
  inv:
    aliases: [invisibility]
    description: Toggle on/off invisibility
  xeffects:
    description: Base command; Reloads plugin